/**
 * SwiftShip AI — public REST API bootstrap.
 *
 * SS-027: This app is the merchant-facing, versioned, rate-limited REST
 * surface that mirrors the GraphQL surface in `apps/api/`. The wire
 * surface (routes, request/response shapes, security schemes) is
 * generated by `tsoa` from the controllers under
 * `apps/api-public/src/controllers/`. On every `nx build api-public` the
 * `tsoa` CLI emits:
 *
 *   1. `src/generated/openapi.json` — committed OpenAPI 3.0 spec
 *      used by `scripts/build-sdks.mjs` to generate the Node, Python
 *      and PHP SDKs.
 *   2. `src/generated/routes.ts` — Express router that we mount
 *      inside the Nest application.
 *
 * Auth is `X-Swiftship-Api-Key` (SS-002), throttling is the
 * `TenantThrottlerGuard` from SS-003. We reuse the same domain
 * services the GraphQL app uses — no business logic is duplicated
 * here.
 */
import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import { Logger, ValidationPipe } from '@nestjs/common';
import type { Request, Response, NextFunction } from 'express';
import { AppModule } from './app.module';
import { mountSwaggerUi } from './swagger-ui/swagger-ui';
import { registerGeneratedRoutes } from './generated-tsoa-bootstrap';
import { tenantKeyMiddleware } from './auth/tenant-key.middleware';
import { tenantContextBindMiddleware } from './auth/tenant-context-bind.middleware';
import { TenantThrottlerMiddleware } from './rate-limit/tenant-throttler.middleware';
import { structuredLogger } from './common/structured-logger';
import openapiJson from './generated/openapi.json';

async function bootstrap() {
  const logger = new Logger('Bootstrap');
  const app = await NestFactory.create(AppModule, { bufferLogs: false });
  app.useLogger(structuredLogger());

  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      transform: true,
      transformOptions: { enableImplicitConversion: true },
    }),
  );

  // -- Order matters -----------------------------------------------------
  // 1. tenant-key resolution (sets req.tenantId) before throttler + ctx
  // 2. tenant-context binding (ALS slot) so repositories can scope
  // 3. tenant throttler (per-tier bucket) — runs after identity is known
  // 4. tsoa routes — handlers + DTO validation
  // 5. swagger UI + openapi.json (mounted on the underlying express app)
  const expressApp = app.getHttpAdapter().getInstance() as import('express').Express;

  // Mount identity and throttling middleware only on /v1/* so the
  // public tracking endpoint (/v1/track/:awb) — which is
  // customer-facing and intentionally unauthenticated — still gets
  // tenant context from the AWB lookup but skips the api-key guard.
  // We accomplish that inside the controllers via @Security('api_key')
  // on the protected methods; the global middleware binds the
  // tenant context if a key WAS supplied (so authenticated and
  // unauthenticated traffic both work).
  expressApp.use('/v1', tenantKeyMiddleware);
  expressApp.use('/v1', tenantContextBindMiddleware);
  expressApp.use('/v1', (req: Request, res: Response, next: NextFunction) => {
    // TenantThrottlerMiddleware reads the resolved tenant from req.tenantId
    // (set by tenantKeyMiddleware) and applies the per-tier bucket from
    // SS-003. It's safe to install this before or after tsoa routes — we
    // install it BEFORE so an over-quota request never reaches a handler.
    TenantThrottlerMiddleware.handle(req as any, res as any, next);
  });

  // -- tsoa-generated routes --------------------------------------------
  // `registerGeneratedRoutes` returns a fresh Express app whose router
  // contains every controller found by tsoa. We copy each `use`/route
  // onto the Nest-managed Express instance so middleware ordering above
  // is preserved.
  registerGeneratedRoutes(expressApp);

  // -- Swagger UI + openapi.json ----------------------------------------
  mountSwaggerUi(expressApp, openapiJson as any);
  expressApp.get('/v1/openapi.json', (_req: Request, res: Response) => {
    res.type('application/json').send(openapiJson);
  });

  // -- Liveness / readiness (matches apps/api/src/health.controller.ts) -
  expressApp.get('/health', (_req: Request, res: Response) => {
    res.json({ status: 'ok', at: new Date().toISOString() });
  });
  expressApp.get('/health/ready', (_req: Request, res: Response) => {
    res.json({ status: 'ready', at: new Date().toISOString() });
  });

  app.enableShutdownHooks();

  const port = Number(process.env.API_REST_PORT ?? 3001);
  await app.listen(port);
  logger.log(`SwiftShip REST API listening on http://localhost:${port}`);
  logger.log(`Swagger UI  →  http://localhost:${port}/docs`);
  logger.log(`OpenAPI     →  http://localhost:${port}/v1/openapi.json`);
}

bootstrap();
