import { Field, InputType, Int, registerEnumType } from '@nestjs/graphql';
import {
  IsEnum,
  IsInt,
  IsOptional,
  IsString,
  Max,
  Min,
} from 'class-validator';

/**
 * The merchant-facing strategies the ranker understands. Surfaced as a
 * GraphQL enum (auto-generated by Apollo as `RateRankingStrategy`).
 *
 * Strategy semantics (see `rate-ranking.service.ts` for the math):
 *  - `cheapest`           — sort by `rate` ascending.
 *  - `fastest`            — sort by `etaDays.max` ascending.
 *  - `best_value`         — `0.4·cost + 0.4·sla − 0.2·score` (default).
 *  - `balanced`           — same formula as `best_value`; flag kept for
 *                           future divergence (e.g. tenant-custom weights).
 *  - `reliability_first`  — sort by `courierScore` descending.
 */
export enum RateRankingStrategy {
  CHEAPEST = 'cheapest',
  FASTEST = 'fastest',
  BEST_VALUE = 'best_value',
  BALANCED = 'balanced',
  RELIABILITY_FIRST = 'reliability_first',
}
registerEnumType(RateRankingStrategy, {
  name: 'RateRankingStrategy',
  description:
    'Strategy for ranking rate-shop quotes. Cheapest / Fastest / Best-Value / Balanced / Reliability-First.',
});

/**
 * Override knobs for a single rate-simulation scenario. All fields are
 * optional — only the ones set are applied on top of the base input.
 *
 *   "What if I bump the weight from 500g to 800g?"
 *     → { weightGrams: 800 }
 *   "What if I switch from PREPAID to COD?"
 *     → { paymentMethod: 'COD' }
 *   "What if I add a ₹100 declared value?"
 *     → { declaredValuePaise: 10000 }
 *   "What if I deliver to a more remote PIN?"
 *     → { destinationPincode: '999999' }
 *   "What if I tighten my SLA cap from 3 days to 2 days?"
 *     → { maxDeliveryDays: 2 }
 *   "What if I require a higher minimum courier score?"
 *     → { minCourierScore: 90 }
 *
 * Money is still in paise. PIN codes are the standard 6-digit Indian
 * postal codes.
 */
@InputType()
export class RateSimulationOverrides {
  /** Override the package weight in grams. */
  @Field(() => Int, { nullable: true, description: 'Override the weight in grams' })
  @IsOptional()
  @IsInt()
  @Min(0)
  weightGrams?: number;

  /** Override the payment method. */
  @Field(() => String, { nullable: true, description: 'Override the payment method' })
  @IsOptional()
  @IsString()
  paymentMethod?: 'PREPAID' | 'COD';

  /** Override the declared value in paise (used as the RTO-loss basis). */
  @Field(() => Int, { nullable: true, description: 'Override the declared value in paise' })
  @IsOptional()
  @IsInt()
  @Min(0)
  declaredValuePaise?: number;

  /** Override the destination PIN code. */
  @Field({ nullable: true, description: 'Override the destination pincode' })
  @IsOptional()
  @IsString()
  destinationPincode?: string;

  /** Override the SLA cap in days. */
  @Field(() => Int, { nullable: true, description: 'Override the SLA cap in days' })
  @IsOptional()
  @IsInt()
  @Min(0)
  maxDeliveryDays?: number;

  /** Override the minimum courier score [0..100]. */
  @Field(() => Int, { nullable: true, description: 'Override the minimum courier score [0..100]' })
  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(100)
  minCourierScore?: number;
}

/**
 * Input for the `rankedRateShop` GraphQL query. Lifts up the
 * `RateQuoteRequest` fields the resolver needs to call
 * `RateShopService.shopRates(req)` and adds two optional ranking
 * constraints: an SLA cap and a minimum courier score.
 */
@InputType()
export class RankedRateShopInput {
  // ---- RateQuoteRequest fields (subset) -----------------------------------

  @Field()
  @IsString()
  originPincode!: string;

  @Field()
  @IsString()
  destinationPincode!: string;

  @Field(() => Int)
  @IsInt()
  @Min(1)
  weightGrams!: number;

  @Field({ defaultValue: 'PREPAID' })
  @IsString()
  paymentMethod!: 'PREPAID' | 'COD';

  /**
   * Declared value (paise). Used as the COD amount proxy for RTO penalty
   * calculation. Optional — defaults to 0 (no RTO penalty computed).
   */
  @Field(() => Int, { nullable: true })
  @IsOptional()
  @IsInt()
  @Min(0)
  declaredValuePaise?: number;

  // ---- Ranking preferences -------------------------------------------------

  @Field(() => RateRankingStrategy, {
    defaultValue: RateRankingStrategy.BEST_VALUE,
  })
  @IsEnum(RateRankingStrategy)
  strategy!: RateRankingStrategy;

  /** SLA cap — carriers with `etaDays.max` greater than this are filtered. */
  @Field(() => Int, { nullable: true })
  @IsOptional()
  @IsInt()
  @Min(0)
  maxDeliveryDays?: number;

  /** Min courier score [0..100]. Carriers below this are filtered. */
  @Field(() => Int, { nullable: true })
  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(100)
  minCourierScore?: number;

  // ---- Simulation overrides (SS-013) ---------------------------------------

  /**
   * Optional "what if" overrides. When set, the resolver clones the
   * input, applies these overrides on top, and runs the ranker against
   * the merged request. The original `RankedRateShopInput` is left
   * untouched — simulations are pure-compute and never persisted.
   */
  @Field(() => RateSimulationOverrides, { nullable: true })
  @IsOptional()
  simulate?: RateSimulationOverrides;
}

