#!/usr/bin/env node
/**
 * generate-openapi.mjs
 *
 * Refreshes `docs/openapi/swagger.yaml` from a running API instance.
 *
 * Why this script exists:
 *   - The REST surface in this repo is small (health, auth, rate-shop, webhooks)
 *     and the public rate-shop controller already has `@ApiTags`/`@ApiOperation`
 *     decorators. `@nestjs/swagger` would auto-generate the spec — but it isn't
 *     installed yet, and adding a runtime dep just for docs is overkill.
 *   - This script pulls `/api/v1/openapi.json` from a running API (or reads the
 *     on-disk `docs/openapi/swagger.yaml` as a fallback) and re-emits it in
 *     YAML form so it diffs cleanly in PRs.
 *
 * Usage:
 *   SWIFTSHIP_OPENAPI_URL=https://sandbox.swiftship.ai/api/v1/openapi.json \
 *     npm run docs:api:openapi
 *
 * If SWIFTSHIP_OPENAPI_URL is unset and the API is reachable at
 * http://localhost:3000/api/v1/openapi.json (the URL it will be served at once
 * SS-037 ships), the script uses that.
 */
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';
import yaml from 'js-yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, '..');
const OUT = resolve(ROOT, 'docs/openapi/swagger.yaml');

const URL = process.env.SWIFTSHIP_OPENAPI_URL ?? 'http://localhost:3000/api/v1/openapi.json';

async function fetchJson(url, timeoutMs = 5_000) {
  const ctl = new AbortController();
  const t = setTimeout(() => ctl.abort(), timeoutMs);
  try {
    const res = await fetch(url, { signal: ctl.signal });
    if (!res.ok) throw new Error(`HTTP ${res.status} from ${url}`);
    return await res.json();
  } finally {
    clearTimeout(t);
  }
}

async function main() {
  let spec;
  let source;
  try {
    spec = await fetchJson(URL);
    source = `live (${URL})`;
  } catch (err) {
    if (existsSync(OUT)) {
      console.warn(`[generate-openapi] could not reach ${URL} (${err.message}); using the on-disk ${OUT} as-is.`);
      return;
    }
    throw new Error(
      `Could not fetch ${URL} (${err.message}) and no on-disk fallback exists. ` +
        `Start the API with 'nx serve api' or set SWIFTSHIP_OPENAPI_URL.`,
    );
  }

  const yml = yaml.dump(spec, { lineWidth: 100, noRefs: true, sortKeys: false });
  writeFileSync(OUT, `# Auto-generated by scripts/generate-openapi.mjs — source: ${source}\n# Do not edit by hand; run \`npm run docs:api:openapi\`.\n\n${yml}`);
  console.log(`[generate-openapi] wrote ${OUT} from ${source}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
